import HowItWorks from "@/components/howitworks";

import Head from "next/head";
import React from "react";

type Props = {};

const HowItWorksPage = (props: Props) => {
  return (
    <>
      <Head>
        <title>How It Works</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.svg" />
      </Head>

      <HowItWorks />
    </>
  );
};

export default HowItWorksPage;
