import Head from "next/head";

Head;

function NotFoundPage() {
  return (
    <>
      <Head>
        <title>NotFound</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.svg" />
      </Head>

      <h1 className="text-2xl text-colBlue02 text-center mt-10">
        Sorry, Page not found!
      </h1>
    </>
  );
}

export default NotFoundPage;
